language: go
go:
- 1.4
install:
- go get -u golang.org/x/tools/cmd/cover
- go get -u github.com/mattn/goveralls
script:
- go test -race -cpu=2 -covermode=count -coverprofile=profile.cov
- $HOME/gopath/bin/goveralls -coverprofile=profile.cov -service=travis-ci
